// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwlbtqpwijeirxcuvhef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3bGJ0cXB3aWplaXJ4Y3V2aGVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNDA5MzQsImV4cCI6MjA1NDgxNjkzNH0.UsvbNW1U3LfbxcBYsm6Kf8Fl6tkMYYga80jRIApiv7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
